apiVersion: apps/v1
kind: Deployment
metadata:
  name: adminmvc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: adminmvc
  template:
    metadata:
      labels:
        app: adminmvc
    spec:
      containers:
        - name: adminmvc
          image: rakeshdev12/usermvc:latest    # ✅ REQUIRED
          imagePullPolicy: Always              # ✅ REQUIRED
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: adminmvc-service
spec:
  selector:
    app: adminmvc
  ports:
    - port: 80
      targetPort: 8080
