apiVersion: apps/v1
kind: Deployment
metadata:
  name: usermvc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: usermvc
  template:
    metadata:
      labels:
        app: usermvc
    spec:
      imagePullSecrets:
        - name: dockerhub-secret
      containers:
        - name: usermvc
          image: rakeshdev12/usermvc:latest    # ✅ REQUIRED
          imagePullPolicy: Always              # ✅ REQUIRED
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: usermvc-service
spec:
  selector:
    app: usermvc
  ports:
    - port: 80
      targetPort: 8080
